[profile.default]
solc_version = "0.8.27"
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
evm_version = "paris"
cbor_metadata = false
bytecode_hash = "none"
